# Generated by Django 6.1.1 on 2026-10-09 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bootstrap", "0012_alter_applyrun_action_alter_configurationplan_action_and_more"),
        ("discovery", "0003_application_observations"),
        ("servers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HostingCreation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.CharField(max_length=64)),
                ("identifier", models.CharField(max_length=24)),
                ("names", models.TextField()),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(blank=True, max_length=10)),
                ("source_setup_needed", models.BooleanField(default=True)),
                ("application", models.CharField(default="php", max_length=12)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("admin_login", models.CharField(blank=True, max_length=60)),
                ("admin_email", models.EmailField(blank=True, max_length=100)),
                ("database_engine", models.CharField(blank=True, max_length=12)),
                ("https", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("authority", models.URLField(blank=True, max_length=500)),
                ("discovery_revision", models.PositiveBigIntegerField()),
                ("ssh_alias", models.CharField(max_length=253)),
                ("host_key", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Preparing site"),
                            ("succeeded", "Site prepared"),
                            ("failed", "Site preparation stopped"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("failure", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="servers.server"
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="HostingCreationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("stage", models.CharField(max_length=32)),
                ("satisfied", models.BooleanField(default=False)),
                (
                    "creation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="hosting.hostingcreation",
                    ),
                ),
                (
                    "discovery",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="discovery.discoveryattempt",
                    ),
                ),
                (
                    "preparation",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bootstrap.planpreparation",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="hostingcreation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("server",),
                name="one_active_hosting_creation",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostingcreation",
            constraint=models.UniqueConstraint(
                fields=("server", "request_key"), name="one_hosting_creation_intent"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostingcreationstep",
            constraint=models.UniqueConstraint(
                fields=("creation", "position"), name="one_step_per_hosting_creation"
            ),
        ),
    ]
