# Generated by Django 6.1.1 on 2026-10-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hosting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostingcreation",
            name="first_access_spki",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="hostingcreation",
            name="node_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
