# Generated by Django 6.1.1 on 2026-09-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bootstrap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanChallenge",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("probe_token", models.CharField(max_length=32)),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("creates_letsencrypt", models.BooleanField()),
                ("creates_backups", models.BooleanField()),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanRenewalObservation",
            fields=[
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="renewal",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("timer_enablement", models.CharField(blank=True, max_length=30)),
                ("timer_state", models.CharField(blank=True, max_length=30)),
                ("last_trigger", models.CharField(blank=True, max_length=60)),
                ("next_elapse", models.CharField(blank=True, max_length=60)),
                ("last_result", models.CharField(blank=True, max_length=30)),
                ("last_status", models.CharField(blank=True, max_length=10)),
                ("last_exit", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunChallenge",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("probe_token", models.CharField(max_length=32)),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("creates_letsencrypt", models.BooleanField()),
                ("creates_backups", models.BooleanField()),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("backup_path", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SetupRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="setup_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TlsRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tls_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
            ],
            options={
                "permissions": [
                    ("view_tlsplan", "Can view TLS plans"),
                    ("prepare_tlsplan", "Can prepare TLS plans"),
                    ("apply_tlsplan", "Can apply TLS plans"),
                    ("issue_certificate", "Can order production certificates"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanRenewalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("deploy_hook", "Deploy hook"),
                            ("renew_wrapper", "Renewal wrapper"),
                            ("dropin", "certbot.service drop-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("mode", models.CharField(max_length=4)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("exists", models.BooleanField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_files",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunRenewalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("deploy_hook", "Deploy hook"),
                            ("renew_wrapper", "Renewal wrapper"),
                            ("dropin", "certbot.service drop-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("mode", models.CharField(max_length=4)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("exists", models.BooleanField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_files",
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
