# Generated by Django 6.1.1 on 2026-09-30 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bootstrap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanChallenge",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("probe_token", models.CharField(max_length=32)),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("creates_letsencrypt", models.BooleanField()),
                ("creates_backups", models.BooleanField()),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunChallenge",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("probe_token", models.CharField(max_length=32)),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("creates_letsencrypt", models.BooleanField()),
                ("creates_backups", models.BooleanField()),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("backup_path", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TlsRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tls_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
            ],
            options={
                "permissions": [
                    ("view_tlsplan", "Can view TLS plans"),
                    ("prepare_tlsplan", "Can prepare TLS plans"),
                    ("apply_tlsplan", "Can apply TLS plans"),
                    ("issue_certificate", "Can order production certificates"),
                ],
                "default_permissions": (),
            },
        ),
    ]
