# Generated by Django 6.1.1 on 2026-09-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bootstrap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanChallenge",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("probe_token", models.CharField(max_length=32)),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("creates_letsencrypt", models.BooleanField()),
                ("creates_backups", models.BooleanField()),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanRenewalObservation",
            fields=[
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="renewal",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("timer_enablement", models.CharField(blank=True, max_length=30)),
                ("timer_state", models.CharField(blank=True, max_length=30)),
                ("last_trigger", models.CharField(blank=True, max_length=60)),
                ("next_elapse", models.CharField(blank=True, max_length=60)),
                ("last_result", models.CharField(blank=True, max_length=30)),
                ("last_status", models.CharField(blank=True, max_length=10)),
                ("last_exit", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunChallenge",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("probe_token", models.CharField(max_length=32)),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("creates_letsencrypt", models.BooleanField()),
                ("creates_backups", models.BooleanField()),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("backup_path", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SetupRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="setup_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TlsRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tls_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
            ],
            options={
                "permissions": [
                    ("view_tlsplan", "Can view TLS plans"),
                    ("prepare_tlsplan", "Can prepare TLS plans"),
                    ("apply_tlsplan", "Can apply TLS plans"),
                    ("issue_certificate", "Can order production certificates"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanRenewalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("deploy_hook", "Deploy hook"),
                            ("renew_wrapper", "Renewal wrapper"),
                            ("dropin", "certbot.service drop-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("mode", models.CharField(max_length=4)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("exists", models.BooleanField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_files",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunRenewalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("deploy_hook", "Deploy hook"),
                            ("renew_wrapper", "Renewal wrapper"),
                            ("dropin", "certbot.service drop-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("mode", models.CharField(max_length=4)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("exists", models.BooleanField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_files",
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ReadinessName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("a", models.TextField(blank=True)),
                ("aaaa", models.TextField(blank=True)),
                ("cname", models.CharField(blank=True, max_length=255)),
                ("caa", models.TextField(blank=True)),
                ("problem", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_names",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="StagingRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staging_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("email", models.EmailField(max_length=254)),
                ("authority", models.CharField(max_length=200)),
                ("terms_accepted", models.BooleanField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="StagingRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staging_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("not_before", models.CharField(blank=True, max_length=60)),
                ("not_after", models.CharField(blank=True, max_length=60)),
                ("names", models.TextField(blank=True)),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanTlsReadiness",
            fields=[
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="readiness",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("authority", models.CharField(max_length=200)),
                ("authority_name", models.CharField(max_length=100)),
                ("webroot", models.CharField(max_length=200)),
                ("ipv6", models.BooleanField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanTlsStaging",
            fields=[
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staging",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("webroot", models.CharField(max_length=200)),
                ("authority", models.CharField(max_length=200)),
                ("authority_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cert_name", models.CharField(max_length=32)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunStaging",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staging",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("webroot", models.CharField(max_length=200)),
                ("authority", models.CharField(max_length=200)),
                ("authority_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cert_name", models.CharField(max_length=32)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="IssuanceRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="issuance_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("email", models.EmailField(max_length=254)),
                ("terms_accepted", models.BooleanField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="IssuanceRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="issuance_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("not_before", models.CharField(blank=True, max_length=60)),
                ("not_after", models.CharField(blank=True, max_length=60)),
                ("names", models.TextField(blank=True)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                ("serial", models.CharField(blank=True, max_length=60)),
                ("key_curve", models.CharField(blank=True, max_length=40)),
                ("key_matches", models.BooleanField(default=False)),
                ("renewal", models.BooleanField(default=False)),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanTlsIssuance",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("webroot", models.CharField(max_length=200)),
                ("authority", models.CharField(max_length=200)),
                ("authority_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cert_name", models.CharField(max_length=32)),
                ("account", models.CharField(blank=True, max_length=254)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="issuance",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunTlsIssuance",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("webroot", models.CharField(max_length=200)),
                ("authority", models.CharField(max_length=200)),
                ("authority_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cert_name", models.CharField(max_length=32)),
                ("account", models.CharField(blank=True, max_length=254)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="issuance",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ActivationRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="activation_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ActivationRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="activation_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("served", models.TextField(blank=True)),
                ("redirect", models.CharField(blank=True, max_length=300)),
                ("rejects_unknown", models.BooleanField(default=False)),
                ("host_checked", models.BooleanField(default=False)),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanTlsActivation",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("https_content", models.TextField()),
                ("https_sha256", models.CharField(max_length=64)),
                ("redirect_content", models.TextField()),
                ("redirect_sha256", models.CharField(max_length=64)),
                ("redirect_only", models.BooleanField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("not_after", models.CharField(max_length=60)),
                ("default_content", models.TextField()),
                ("default_sha256", models.CharField(max_length=64)),
                ("creates_default", models.BooleanField()),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="activation",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunTlsActivation",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("names", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("preimage", models.TextField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("https_content", models.TextField()),
                ("https_sha256", models.CharField(max_length=64)),
                ("redirect_content", models.TextField()),
                ("redirect_sha256", models.CharField(max_length=64)),
                ("redirect_only", models.BooleanField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("not_after", models.CharField(max_length=60)),
                ("default_content", models.TextField()),
                ("default_sha256", models.CharField(max_length=64)),
                ("creates_default", models.BooleanField()),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="activation",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("backup_path", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
