# Generated by Django 6.1.1 on 2026-10-04 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0001_initial"),
        ("servers", "0001_initial"),
        ("tls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("names", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("authority", models.URLField(max_length=500)),
                ("ssh_alias", models.CharField(max_length=253)),
                ("host_key", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Installing"),
                            ("succeeded", "HTTPS installed"),
                            ("failed", "Installation stopped"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("failure", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="servers.server"
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CertificateInstallationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tls.certificateinstallation",
                    ),
                ),
                (
                    "preparation",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bootstrap.planpreparation",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="certificateinstallation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("server",),
                name="one_active_certificate_installation",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificateinstallationstep",
            constraint=models.UniqueConstraint(
                fields=("installation", "position"), name="one_step_per_certificate_installation"
            ),
        ),
    ]
