# Generated by Django 6.1.1 on 2026-10-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tls", "0002_certificateinstallation_certificateinstallationstep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateinstallation",
            name="discovery_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
