# Generated by Django 6.1.1 on 2026-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tls", "0003_certificateinstallation_discovery_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantlsreadiness",
            name="addresses_collected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plantlsreadiness",
            name="server_ipv4",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plantlsreadiness",
            name="server_ipv6",
            field=models.TextField(blank=True),
        ),
    ]
