# Generated by Django 6.1.1 on 2026-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tls", "0004_plantlsreadiness_addresses_collected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planchallenge",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="plantlsactivation",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="plantlsissuance",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="plantlsreadiness",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="plantlsstaging",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="runchallenge",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="runstaging",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="runtlsactivation",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="runtlsissuance",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
