# Generated by Django 6.1.1 on 2026-10-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node_runtimes", "0002_noderuntimesnapshot_runtimechange_runtimechangestep_and_more"),
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtimechange",
            name="server",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="node_runtime_changes",
                to="servers.server",
            ),
        ),
    ]
