# Generated by Django 6.1.1 on 2026-09-27 06:06

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "ssh_alias",
                    models.CharField(
                        max_length=253,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("\\A[A-Za-z0-9_][A-Za-z0-9._-]*\\Z"),
                                "Enter an SSH alias, not a pattern or command.",
                            )
                        ],
                        verbose_name="SSH alias",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ssh_alias",),
                        name="servers_server_unique_ssh_alias",
                        violation_error_code="unique",
                        violation_error_message=(
                            "Another server is already registered with this alias."
                        ),
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ssh_alias", ""), _negated=True),
                        name="servers_server_ssh_alias_required",
                    ),
                ],
            },
        ),
    ]
