# Generated by Django 6.0.8 on 2026-09-26 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "hostname",
                    models.CharField(
                        max_length=253,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[A-Za-z0-9][A-Za-z0-9.:-]*\\Z",
                                "Enter a hostname, IP address, or SSH alias "
                                "without spaces or shell characters.",
                            )
                        ],
                    ),
                ),
                (
                    "ssh_port",
                    models.PositiveIntegerField(
                        default=22,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "ssh_user",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z_][a-z0-9_-]*\\Z", "Enter a Linux username."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
