# Generated by Django 6.1.1 on 2026-09-26 06:04, then ordered to keep existing connection
# details for reconciliation before the explicit connection fields are removed.

import re

import django.core.validators
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import Value
from django.db.models.functions import Cast, Concat

LEGACY = re.compile(r"\A(?P<user>[^@]*)@(?P<host>.*):(?P<port>\d+)\Z")


def historical_servers(apps: Apps) -> models.Manager[models.Model]:
    # The historical model has fields the current Server model lacks; type it generically.
    server_model: type[models.Model] = apps.get_model("servers", "Server")
    return server_model._default_manager


def record_legacy_connections(apps: Apps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Keep explicit details for the operator. They are not treated as an SSH alias."""
    historical_servers(apps).update(
        legacy_connection=Concat(
            "ssh_user", Value("@"), "hostname", Value(":"), Cast("ssh_port", models.CharField())
        )
    )


def restore_explicit_connections(apps: Apps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    servers = historical_servers(apps)
    for pk, legacy, alias in servers.values_list("pk", "legacy_connection", "ssh_alias"):
        match = LEGACY.match(legacy)
        if match:
            fields = {"ssh_user": match["user"], "hostname": match["host"]}
            servers.filter(pk=pk).update(ssh_port=int(match["port"]), **fields)
        else:
            # Reconciled records only have an alias, which OpenSSH tools accept as a host.
            servers.filter(pk=pk).update(hostname=alias)


class Migration(migrations.Migration):
    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="legacy_connection",
            field=models.CharField(blank=True, editable=False, max_length=400),
        ),
        migrations.AddField(
            model_name="server",
            name="ssh_alias",
            field=models.CharField(
                blank=True,
                max_length=253,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("\\A[A-Za-z0-9_][A-Za-z0-9._-]*\\Z"),
                        "Enter an SSH alias, not a pattern or command.",
                    )
                ],
                verbose_name="SSH alias",
            ),
        ),
        migrations.RunPython(record_legacy_connections, restore_explicit_connections),
        # Defaults let a reversal re-add the removed columns to reconciled records.
        migrations.AlterField(
            model_name="server",
            name="hostname",
            field=models.CharField(default="", max_length=253),
        ),
        migrations.AlterField(
            model_name="server",
            name="ssh_user",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.RemoveField(
            model_name="server",
            name="hostname",
        ),
        migrations.RemoveField(
            model_name="server",
            name="ssh_port",
        ),
        migrations.RemoveField(
            model_name="server",
            name="ssh_user",
        ),
        migrations.AddConstraint(
            model_name="server",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ssh_alias", ""), _negated=True),
                fields=("ssh_alias",),
                name="servers_server_unique_ssh_alias",
                violation_error_message="Another server is already registered with this alias.",
            ),
        ),
        migrations.AddConstraint(
            model_name="server",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ssh_alias", ""), _negated=True),
                    models.Q(("legacy_connection", ""), _negated=True),
                    _connector="OR",
                ),
                name="servers_server_alias_or_legacy_connection",
            ),
        ),
    ]
