# Generated by Django 6.1.1 on 2026-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers", "0002_ssh_alias"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="server",
            name="servers_server_unique_ssh_alias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ssh_alias", ""), _negated=True),
                fields=("ssh_alias",),
                name="servers_server_unique_ssh_alias",
                violation_error_code="unique",
                violation_error_message="Another server is already registered with this alias.",
            ),
        ),
    ]
