# Generated by Django 6.1.1 on 2026-10-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bootstrap", "0005_alter_applyrun_action_alter_applyrun_execution_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanWpcliTool",
            fields=[
                ("version", models.CharField(max_length=20)),
                ("phar_url", models.URLField(max_length=300)),
                ("signature_url", models.URLField(max_length=300)),
                ("key_url", models.URLField(max_length=300)),
                ("fingerprint", models.CharField(max_length=40)),
                ("sha256", models.CharField(max_length=64)),
                ("path", models.CharField(max_length=200)),
                ("creates_directory", models.BooleanField()),
                ("exists", models.BooleanField()),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wpcli_tool",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunWpcliTool",
            fields=[
                ("version", models.CharField(max_length=20)),
                ("phar_url", models.URLField(max_length=300)),
                ("signature_url", models.URLField(max_length=300)),
                ("key_url", models.URLField(max_length=300)),
                ("fingerprint", models.CharField(max_length=40)),
                ("sha256", models.CharField(max_length=64)),
                ("path", models.CharField(max_length=200)),
                ("creates_directory", models.BooleanField()),
                ("exists", models.BooleanField()),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wpcli_tool",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WpcliRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wpcli_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
