# Generated by Django 6.1.1 on 2026-10-08 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0006_wordpress_runtime"),
        ("wordpress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanWordpressRuntime",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("socket", models.CharField(max_length=100)),
                ("probe_token", models.CharField(max_length=32)),
                ("probe_path", models.CharField(max_length=100)),
                ("probe_content", models.TextField()),
                ("probe_sha256", models.CharField(max_length=64)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_runtime",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RuntimeRunResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="runtime_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("problems", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunWordpressRuntime",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("socket", models.CharField(max_length=100)),
                ("probe_token", models.CharField(max_length=32)),
                ("probe_path", models.CharField(max_length=100)),
                ("probe_content", models.TextField()),
                ("probe_sha256", models.CharField(max_length=64)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_runtime",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WordpressRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanRuntimeCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=60)),
                ("package", models.CharField(blank=True, max_length=60)),
                ("cli", models.BooleanField()),
                ("fpm", models.BooleanField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled in the CLI and PHP-FPM"),
                            ("planned", "Installed by this plan"),
                            ("unavailable", "Not available"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runtime_capabilities",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunRuntimeCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=60)),
                ("package", models.CharField(blank=True, max_length=60)),
                ("cli", models.BooleanField()),
                ("fpm", models.BooleanField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled in the CLI and PHP-FPM"),
                            ("planned", "Installed by this plan"),
                            ("unavailable", "Not available"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runtime_capabilities",
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
