# Generated by Django 6.1.1 on 2026-10-09 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0007_wordpress_installation_review"),
        ("wordpress", "0002_php_runtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallationRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="installation_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("canonical_name", models.CharField(max_length=46)),
                ("title", models.CharField(max_length=100)),
                ("admin_login", models.CharField(max_length=60)),
                ("admin_email", models.CharField(max_length=100)),
            ],
            options={
                "permissions": [
                    ("view_wordpressplan", "Can view WordPress plans"),
                    ("prepare_wordpressplan", "Can prepare WordPress plans"),
                    ("install_wordpress", "Can install WordPress from a reviewed plan"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanWordpressInstall",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("socket", models.CharField(max_length=100)),
                ("ipv6", models.BooleanField()),
                ("names", models.CharField(max_length=520)),
                ("canonical_name", models.CharField(max_length=46)),
                ("url", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=100)),
                ("admin_login", models.CharField(max_length=60)),
                ("admin_email", models.CharField(max_length=100)),
                ("certificate_sha256", models.CharField(max_length=64)),
                ("certificate_not_after", models.CharField(max_length=40)),
                ("tool_version", models.CharField(max_length=20)),
                ("tool_path", models.CharField(max_length=200)),
                ("tool_sha256", models.CharField(max_length=64)),
                ("core_version", models.CharField(max_length=20)),
                ("core_locale", models.CharField(max_length=10)),
                ("archive_url", models.CharField(max_length=200)),
                ("archive_bytes", models.PositiveBigIntegerField()),
                ("archive_sha256", models.CharField(max_length=64)),
                ("max_archive_bytes", models.PositiveBigIntegerField()),
                ("max_tree_bytes", models.PositiveBigIntegerField()),
                ("max_entries", models.PositiveIntegerField()),
                ("max_file_bytes", models.PositiveBigIntegerField()),
                ("memory_max_bytes", models.PositiveBigIntegerField()),
                ("runtime_limit_seconds", models.PositiveIntegerField()),
                ("preimage_sha256", models.CharField(max_length=64)),
                ("gate_sha256", models.CharField(max_length=64)),
                ("gate_content", models.TextField()),
                ("ready_sha256", models.CharField(max_length=64)),
                ("ready_content", models.TextField()),
                ("placeholder_sha256", models.CharField(max_length=64)),
                ("placeholder_present", models.BooleanField()),
                ("loader_sha256", models.CharField(max_length=64)),
                ("public_root", models.CharField(max_length=100)),
                ("private_configuration", models.CharField(max_length=100)),
                ("database_name", models.CharField(max_length=25)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_install",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
