# Generated by Django 6.1.1 on 2026-10-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0009_wordpress_inspection"),
        ("wordpress", "0004_wordpress_installation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inspection_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("inspect", "Inspect WordPress"),
                            ("core", "Verify core checksums"),
                            ("plugins", "Verify repository plugin checksums"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "inspect_wordpress",
                        "Can run an explicit WordPress inspection from a reviewed plan",
                    )
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inspection_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("inspect", "Inspect WordPress"),
                            ("core", "Verify core checksums"),
                            ("plugins", "Verify repository plugin checksums"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("available", "Available"), ("unavailable", "Unavailable")],
                        max_length=12,
                    ),
                ),
                ("why", models.CharField(blank=True, max_length=20)),
                ("retrieved_at", models.DateTimeField()),
                ("reported_at", models.DateTimeField(null=True)),
                ("core_version", models.CharField(blank=True, max_length=40)),
                ("core_installed", models.BooleanField(null=True)),
                (
                    "integrity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("match", "Matches the official checksums"),
                            ("mismatch", "Differs from the official checksums"),
                            ("unavailable", "Could not be checked"),
                        ],
                        max_length=12,
                    ),
                ),
                ("integrity_why", models.CharField(blank=True, max_length=20)),
                ("modified", models.PositiveIntegerField(default=0)),
                ("missing", models.PositiveIntegerField(default=0)),
                ("extra", models.PositiveIntegerField(default=0)),
                ("files", models.TextField(blank=True)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanWordpressInspection",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("canonical_name", models.CharField(max_length=46)),
                ("url", models.CharField(max_length=60)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("inspect", "Inspect WordPress"),
                            ("core", "Verify core checksums"),
                            ("plugins", "Verify repository plugin checksums"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tool_version", models.CharField(max_length=20)),
                ("tool_path", models.CharField(max_length=200)),
                ("tool_sha256", models.CharField(max_length=64)),
                ("core_version", models.CharField(max_length=40)),
                ("core_locale", models.CharField(max_length=10)),
                ("core_qualified", models.BooleanField()),
                ("configuration_sha256", models.CharField(max_length=64)),
                ("targets", models.TextField(blank=True)),
                ("max_file_bytes", models.PositiveBigIntegerField()),
                ("memory_max_bytes", models.PositiveBigIntegerField()),
                ("runtime_limit_seconds", models.PositiveIntegerField()),
                ("command_seconds", models.PositiveIntegerField()),
                ("budget_seconds", models.PositiveIntegerField()),
                ("body_sha256", models.CharField(blank=True, max_length=64)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_inspection",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunWordpressInspection",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("canonical_name", models.CharField(max_length=46)),
                ("url", models.CharField(max_length=60)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("inspect", "Inspect WordPress"),
                            ("core", "Verify core checksums"),
                            ("plugins", "Verify repository plugin checksums"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tool_version", models.CharField(max_length=20)),
                ("tool_path", models.CharField(max_length=200)),
                ("tool_sha256", models.CharField(max_length=64)),
                ("core_version", models.CharField(max_length=40)),
                ("core_locale", models.CharField(max_length=10)),
                ("core_qualified", models.BooleanField()),
                ("configuration_sha256", models.CharField(max_length=64)),
                ("targets", models.TextField(blank=True)),
                ("max_file_bytes", models.PositiveBigIntegerField()),
                ("memory_max_bytes", models.PositiveBigIntegerField()),
                ("runtime_limit_seconds", models.PositiveIntegerField()),
                ("command_seconds", models.PositiveIntegerField()),
                ("budget_seconds", models.PositiveIntegerField()),
                ("body_sha256", models.CharField(blank=True, max_length=64)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_inspection",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("plugin", "Plugin"),
                            ("mu-plugin", "Must-use plugin"),
                            ("dropin", "Drop-in"),
                            ("theme", "Theme"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("version", models.CharField(blank=True, max_length=40)),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("match", "Matches the official checksums"),
                            ("mismatch", "Differs from the official checksums"),
                            ("unavailable", "Could not be checked"),
                        ],
                        max_length=12,
                    ),
                ),
                ("why", models.CharField(blank=True, max_length=20)),
                ("modified", models.PositiveIntegerField(default=0)),
                ("added", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="wordpress.inspectionresult",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
    ]
