# Generated by Django 6.1.1 on 2026-10-09 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0010_wordpress_maintenance"),
        ("wordpress", "0005_wordpress_inspection"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="maintenance_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("rewrite", "Flush rewrite rules"),
                            ("cache", "Flush object cache"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("maintain_wordpress", "Can run WordPress maintenance from a reviewed plan")
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="MaintenanceResult",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="maintenance_result",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("rewrite", "Flush rewrite rules"),
                            ("cache", "Flush object cache"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("available", "Available"), ("unavailable", "Unavailable")],
                        max_length=12,
                    ),
                ),
                ("why", models.CharField(blank=True, max_length=20)),
                ("retrieved_at", models.DateTimeField()),
                ("reported_at", models.DateTimeField(null=True)),
                (
                    "rules",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stored", "Rewrite rules are stored"),
                            ("empty", "No rewrite rules are stored"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanWordpressMaintenance",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("canonical_name", models.CharField(max_length=46)),
                ("url", models.CharField(max_length=60)),
                ("tool_version", models.CharField(max_length=20)),
                ("tool_path", models.CharField(max_length=200)),
                ("tool_sha256", models.CharField(max_length=64)),
                ("core_version", models.CharField(max_length=40)),
                ("core_locale", models.CharField(max_length=10)),
                ("core_qualified", models.BooleanField()),
                ("configuration_sha256", models.CharField(max_length=64)),
                ("targets", models.TextField(blank=True)),
                ("max_file_bytes", models.PositiveBigIntegerField()),
                ("memory_max_bytes", models.PositiveBigIntegerField()),
                ("runtime_limit_seconds", models.PositiveIntegerField()),
                ("command_seconds", models.PositiveIntegerField()),
                ("budget_seconds", models.PositiveIntegerField()),
                ("body_sha256", models.CharField(blank=True, max_length=64)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("rewrite", "Flush rewrite rules"),
                            ("cache", "Flush object cache"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_maintenance",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunWordpressMaintenance",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("canonical_name", models.CharField(max_length=46)),
                ("url", models.CharField(max_length=60)),
                ("tool_version", models.CharField(max_length=20)),
                ("tool_path", models.CharField(max_length=200)),
                ("tool_sha256", models.CharField(max_length=64)),
                ("core_version", models.CharField(max_length=40)),
                ("core_locale", models.CharField(max_length=10)),
                ("core_qualified", models.BooleanField()),
                ("configuration_sha256", models.CharField(max_length=64)),
                ("targets", models.TextField(blank=True)),
                ("max_file_bytes", models.PositiveBigIntegerField()),
                ("memory_max_bytes", models.PositiveBigIntegerField()),
                ("runtime_limit_seconds", models.PositiveIntegerField()),
                ("command_seconds", models.PositiveIntegerField()),
                ("budget_seconds", models.PositiveIntegerField()),
                ("body_sha256", models.CharField(blank=True, max_length=64)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("rewrite", "Flush rewrite rules"),
                            ("cache", "Flush object cache"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_maintenance",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
