# Generated by Django 6.1.1 on 2026-10-09 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0015_runtime_server_removal"),
        ("wordpress", "0007_wordpress_maintenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="installationrequest",
            name="first_access_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="installationrequest",
            name="first_access_spki",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="planwordpressfinish",
            name="first_access_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="planwordpressfinish",
            name="first_access_spki",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="planwordpressinstall",
            name="first_access_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="planwordpressinstall",
            name="first_access_spki",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="runwordpressfinish",
            name="first_access_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="runwordpressfinish",
            name="first_access_spki",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="runwordpressinstall",
            name="first_access_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="runwordpressinstall",
            name="first_access_spki",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.CreateModel(
            name="FirstAccessDelivery",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
                ("key_sha256", models.CharField(max_length=64)),
                ("ciphertext", models.CharField(blank=True, max_length=684)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                ("retrieved_at", models.DateTimeField(null=True)),
                ("unavailable", models.BooleanField(default=False)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
