# Generated by Django 6.1.1 on 2026-10-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0018_alter_applyrun_action_alter_configurationplan_action_and_more"),
        ("wordpress", "0008_installationrequest_first_access_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessResetRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="access_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("admin_login", models.CharField(max_length=60)),
                ("first_access_spki", models.CharField(max_length=1024)),
                ("first_access_expires_at", models.DateTimeField()),
            ],
            options={
                "permissions": [
                    (
                        "manage_wordpress_credentials",
                        "Can explicitly reset WordPress administrator access",
                    )
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanWordpressAccess",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("canonical_name", models.CharField(max_length=46)),
                ("url", models.CharField(max_length=60)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("inspect", "Inspect WordPress"),
                            ("core", "Verify core checksums"),
                            ("plugins", "Verify repository plugin checksums"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tool_version", models.CharField(max_length=20)),
                ("tool_path", models.CharField(max_length=200)),
                ("tool_sha256", models.CharField(max_length=64)),
                ("core_version", models.CharField(max_length=40)),
                ("core_locale", models.CharField(max_length=10)),
                ("core_qualified", models.BooleanField()),
                ("configuration_sha256", models.CharField(max_length=64)),
                ("targets", models.TextField(blank=True)),
                ("max_file_bytes", models.PositiveBigIntegerField()),
                ("memory_max_bytes", models.PositiveBigIntegerField()),
                ("runtime_limit_seconds", models.PositiveIntegerField()),
                ("command_seconds", models.PositiveIntegerField()),
                ("budget_seconds", models.PositiveIntegerField()),
                ("body_sha256", models.CharField(blank=True, max_length=64)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                ("account_id", models.PositiveBigIntegerField()),
                ("admin_login", models.CharField(max_length=60)),
                ("admin_email", models.CharField(max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("site_digest", models.CharField(max_length=64)),
                ("wpcli_digest", models.CharField(max_length=64)),
                ("state_digest", models.CharField(max_length=64)),
                ("account_digest", models.CharField(max_length=64)),
                ("password_digest", models.CharField(max_length=64)),
                ("first_access_spki", models.CharField(max_length=1024)),
                ("first_access_expires_at", models.DateTimeField()),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_access",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RunWordpressAccess",
            fields=[
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=3)),
                ("php_supply", models.CharField(default="ubuntu", max_length=10)),
                ("site_revision", models.PositiveSmallIntegerField()),
                ("site_user", models.CharField(max_length=32)),
                ("uid", models.PositiveIntegerField()),
                ("gid", models.PositiveIntegerField()),
                ("canonical_name", models.CharField(max_length=46)),
                ("url", models.CharField(max_length=60)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("inspect", "Inspect WordPress"),
                            ("core", "Verify core checksums"),
                            ("plugins", "Verify repository plugin checksums"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tool_version", models.CharField(max_length=20)),
                ("tool_path", models.CharField(max_length=200)),
                ("tool_sha256", models.CharField(max_length=64)),
                ("core_version", models.CharField(max_length=40)),
                ("core_locale", models.CharField(max_length=10)),
                ("core_qualified", models.BooleanField()),
                ("configuration_sha256", models.CharField(max_length=64)),
                ("targets", models.TextField(blank=True)),
                ("max_file_bytes", models.PositiveBigIntegerField()),
                ("memory_max_bytes", models.PositiveBigIntegerField()),
                ("runtime_limit_seconds", models.PositiveIntegerField()),
                ("command_seconds", models.PositiveIntegerField()),
                ("budget_seconds", models.PositiveIntegerField()),
                ("body_sha256", models.CharField(blank=True, max_length=64)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
                ("account_id", models.PositiveBigIntegerField()),
                ("admin_login", models.CharField(max_length=60)),
                ("admin_email", models.CharField(max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("site_digest", models.CharField(max_length=64)),
                ("wpcli_digest", models.CharField(max_length=64)),
                ("state_digest", models.CharField(max_length=64)),
                ("account_digest", models.CharField(max_length=64)),
                ("password_digest", models.CharField(max_length=64)),
                ("first_access_spki", models.CharField(max_length=1024)),
                ("first_access_expires_at", models.DateTimeField()),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wordpress_access",
                        serialize=False,
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AccessResetIntent",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="access_intent",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("status", models.CharField(default="active", max_length=12)),
                ("failure", models.TextField(blank=True)),
                (
                    "run",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bootstrap.applyrun",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
