# Generated by Django 6.1.1 on 2026-09-29 15:24

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPreparation",
            fields=[
                (
                    "remoteoperation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="operations.remoteoperation",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx profile"),
                            ("php", "PHP profile (FPM and CLI)"),
                            ("mariadb", "MariaDB profile"),
                            ("postgresql", "PostgreSQL profile"),
                            ("metadata_refresh", "Package metadata refresh"),
                            ("clear_results", "Clear finished bootstrap runs"),
                            ("site_http", "HTTP PHP site"),
                            ("php_mysql", "PHP MariaDB driver"),
                            ("php_pgsql", "PHP PostgreSQL driver"),
                            ("database_mariadb", "MariaDB site database"),
                            ("database_postgresql", "PostgreSQL site database"),
                            ("database_inspection", "Privileged database inspection"),
                            ("tls_challenge", "Site challenge route"),
                            ("certbot", "Certbot renewal setup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
            bases=("operations.remoteoperation",),
        ),
        migrations.CreateModel(
            name="ApplyRun",
            fields=[
                (
                    "remoteoperation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="operations.remoteoperation",
                    ),
                ),
                ("plan_number", models.PositiveBigIntegerField(unique=True)),
                ("requested_by_name", models.CharField(max_length=150)),
                ("server_name", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx profile"),
                            ("php", "PHP profile (FPM and CLI)"),
                            ("mariadb", "MariaDB profile"),
                            ("postgresql", "PostgreSQL profile"),
                            ("metadata_refresh", "Package metadata refresh"),
                            ("clear_results", "Clear finished bootstrap runs"),
                            ("site_http", "HTTP PHP site"),
                            ("php_mysql", "PHP MariaDB driver"),
                            ("php_pgsql", "PHP PostgreSQL driver"),
                            ("database_mariadb", "MariaDB site database"),
                            ("database_postgresql", "PostgreSQL site database"),
                            ("database_inspection", "Privileged database inspection"),
                            ("tls_challenge", "Site challenge route"),
                            ("certbot", "Certbot renewal setup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("intent", models.CharField(max_length=200)),
                ("profile_revision", models.PositiveSmallIntegerField()),
                ("release", models.CharField(max_length=5)),
                ("reviewed_host_key", models.CharField(max_length=200)),
                ("boot_id", models.CharField(max_length=36)),
                ("admission_deadline_centiseconds", models.BigIntegerField()),
                ("admission_expires_at", models.DateTimeField()),
                ("effects", models.TextField()),
                ("reviewed_changes", models.TextField(blank=True)),
                ("unit_name", models.CharField(max_length=80, unique=True)),
                ("invocation_id", models.CharField(blank=True, max_length=32)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("dpkg_status_before", models.CharField(blank=True, max_length=64)),
                ("auto_marks_before", models.CharField(blank=True, max_length=64)),
                (
                    "execution",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not submitted"),
                            ("submitted", "Submitted; not yet confirmed on the server"),
                            ("not_found", "No native record found"),
                            ("running", "Running on the server"),
                            ("succeeded", "Completed successfully"),
                            ("lock_conflict", "Refused: another change holds the mutation lock"),
                            ("unsafe_lock", "Refused: the lock directory is not safe"),
                            ("boot_changed", "Refused: the server restarted after review"),
                            ("expired", "Refused: the admission deadline had passed"),
                            (
                                "other_run_active",
                                "Refused: another bootstrap run still has processes",
                            ),
                            ("drift", "Refused: the reviewed evidence changed"),
                            (
                                "renewal_active",
                                "Refused: scheduled certificate renewal still has processes",
                            ),
                            (
                                "inhibition_failed",
                                "Refused: Certbot's packaged renewal could not be inhibited",
                            ),
                            ("package_manager_busy", "Refused: the package manager is busy"),
                            ("capacity", "Refused: too many finished runs are retained"),
                            (
                                "transaction_refused",
                                "Refused: APT's actual transaction differed from the reviewed one",
                            ),
                            (
                                "account_busy",
                                "Refused: the account tool could not change the accounts",
                            ),
                            (
                                "driver_unavailable",
                                "Refused: the site's pool does not run as reviewed with the driver",
                            ),
                            ("principal_conflict", "Refused: the principal already existed"),
                            (
                                "statement_refused",
                                "Refused: the engine rejected the first statement",
                            ),
                            ("partial", "Stopped after changing the server: partly applied"),
                            ("failed", "Failed"),
                            ("install_not_started", "Failed before dpkg changed any package"),
                            ("install_failed", "Failed after dpkg changed packages"),
                            ("service_failed", "Failed to enable or start the service"),
                            (
                                "validation_failed",
                                "Changed, but the configuration syntax check failed",
                            ),
                            ("reload_failed", "Changed, but the service reload failed"),
                            ("timed_out", "Stopped at the runtime limit"),
                            ("killed", "Terminated by a signal"),
                            (
                                "outcome_unknown",
                                "Outcome unknown: no native record of the run remains",
                            ),
                        ],
                        default="not_submitted",
                        max_length=30,
                    ),
                ),
                ("exit_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "verification",
                    models.CharField(
                        choices=[
                            ("pending", "Not checked yet"),
                            ("passed", "Postconditions hold"),
                            ("failed", "Postconditions do not hold"),
                            ("unavailable", "Could not be checked"),
                            ("not_applicable", "Not applicable: the execution did not succeed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("unknown_acknowledged_by_name", models.CharField(blank=True, max_length=150)),
                ("unknown_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("closure_requested_at", models.DateTimeField(blank=True, null=True)),
                ("closure_blocked", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unknown_acknowledged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
            bases=("operations.remoteoperation",),
        ),
        migrations.CreateModel(
            name="ConfigurationPlan",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="plan",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx profile"),
                            ("php", "PHP profile (FPM and CLI)"),
                            ("mariadb", "MariaDB profile"),
                            ("postgresql", "PostgreSQL profile"),
                            ("metadata_refresh", "Package metadata refresh"),
                            ("clear_results", "Clear finished bootstrap runs"),
                            ("site_http", "HTTP PHP site"),
                            ("php_mysql", "PHP MariaDB driver"),
                            ("php_pgsql", "PHP PostgreSQL driver"),
                            ("database_mariadb", "MariaDB site database"),
                            ("database_postgresql", "PostgreSQL site database"),
                            ("database_inspection", "Privileged database inspection"),
                            ("tls_challenge", "Site challenge route"),
                            ("certbot", "Certbot renewal setup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("profile_revision", models.PositiveSmallIntegerField()),
                ("intent", models.CharField(max_length=200)),
                ("eligible", models.BooleanField()),
                ("no_changes", models.BooleanField(default=False)),
                ("ssh_alias", models.CharField(max_length=253, verbose_name="SSH alias")),
                ("host_key", models.CharField(max_length=200)),
                ("boot_id", models.CharField(blank=True, max_length=36)),
                ("uptime_centiseconds", models.BigIntegerField(null=True)),
                ("admission_deadline_centiseconds", models.BigIntegerField(null=True)),
                ("collected_at", models.DateTimeField()),
                ("admission_expires_at", models.DateTimeField()),
                ("os_name", models.CharField(blank=True, max_length=200)),
                ("release", models.CharField(blank=True, max_length=5)),
                ("architecture", models.CharField(blank=True, max_length=20)),
                ("apt_version", models.CharField(blank=True, max_length=100)),
                ("dpkg_version", models.CharField(blank=True, max_length=100)),
                ("systemd_version", models.CharField(blank=True, max_length=100)),
                (
                    "privilege",
                    models.CharField(
                        choices=[
                            ("root", "Root"),
                            ("sudo", "Noninteractive sudo"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("prepare_configurationplan", "Can prepare configuration plans"),
                    ("apply_configurationplan", "Can apply reviewed configuration plans"),
                    ("clear_native_results", "Can clear terminal native execution results"),
                ],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="PlanRootPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("installed", models.BooleanField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roots",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanRefusal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsupported_platform", "Unsupported platform"),
                            ("privilege", "Privilege unavailable"),
                            ("package_health", "Package database needs attention"),
                            ("held_package", "Held package"),
                            ("apt_hook", "Unknown APT hook"),
                            ("apt_configuration", "Unsupported APT configuration"),
                            ("package_source", "Unqualified package source"),
                            ("package_metadata", "Package indexes unavailable"),
                            ("installed_package_change", "Installed package would change"),
                            ("customized", "Customized configuration"),
                            ("leftover", "Leftover configuration"),
                            ("service_unit", "Service unit needs attention"),
                            ("listener", "Conflicting listener"),
                            ("unsupported_version", "Unsupported release installed"),
                            ("conflict", "Conflicting installation"),
                            ("administration", "Administrative access not established"),
                            ("simulation", "Package simulation refused"),
                            ("incomplete", "Incomplete evidence"),
                            ("collision", "Existing resource"),
                            ("unsupported_layout", "Unsupported configuration layout"),
                            ("partial_site", "Incomplete site"),
                            ("prerequisite", "Prerequisite missing"),
                            ("payload_too_large", "Too large to submit"),
                            ("partial_binding", "Incomplete database binding"),
                            ("existing_binding", "Existing database binding"),
                            ("automation", "Other certificate automation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refusals",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanPostcondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postconditions",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanNativeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("unit_name", models.CharField(max_length=80)),
                ("invocation_id", models.CharField(max_length=32)),
                ("active_state", models.CharField(max_length=30)),
                ("sub_state", models.CharField(max_length=30)),
                ("result", models.CharField(max_length=30)),
                ("exec_main_status", models.PositiveSmallIntegerField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="native_units",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("platform", "Platform and boot"),
                            ("privilege", "Privilege"),
                            ("apt_configuration", "Effective APT configuration"),
                            ("apt_hooks", "APT hooks"),
                            ("apt_sources", "APT sources"),
                            ("apt_preferences", "APT preferences"),
                            ("package_indexes", "Package indexes"),
                            ("dpkg_status", "Relevant package states"),
                            ("package_holds", "Package holds"),
                            ("auto_marks", "Automatic installation marks"),
                            ("simulation", "APT simulation"),
                            ("web_configuration", "Web-stack configuration"),
                            ("service_units", "Service units"),
                            ("listeners", "Listeners"),
                            ("administration", "Administrative access"),
                            ("data_paths", "Data directories and option files"),
                            ("apt_revalidation", "APT evidence rechecked before applying"),
                            ("retained_units", "Retained bootstrap units"),
                            (
                                "package_revalidation",
                                "Package and service evidence rechecked before applying",
                            ),
                            ("site_revalidation", "Site evidence rechecked before applying"),
                            (
                                "renewal_revalidation",
                                "Renewal evidence rechecked before applying",
                            ),
                            ("nginx_closure", "Nginx configuration"),
                            ("fpm_closure", "PHP-FPM configuration"),
                            ("accounts", "Accounts and groups"),
                            ("allocation", "Account allocation policy"),
                            ("site_paths", "Site paths and ancestors"),
                            ("catalog", "Database catalog"),
                            (
                                "catalog_revalidation",
                                "Database catalog rechecked before and during applying",
                            ),
                            ("catalog_after", "Database catalog after applying"),
                            ("driver", "PHP driver rechecked before applying"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("summary", models.CharField(max_length=300)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("no_changes", "No changes"),
                            ("packages", "Package installation"),
                            ("package_guard", "Transaction guard"),
                            ("maintainer_start", "Package maintainer service start"),
                            ("http_listener", "Default HTTP listener"),
                            ("local_socket", "Local socket"),
                            ("database_listeners", "Local database listeners"),
                            ("data_directory", "Data directory initialization"),
                            ("service_enable", "Service enablement"),
                            ("service_start", "Service start"),
                            ("needrestart", "Native restart policy"),
                            ("index_update", "Package index update"),
                            ("third_party_sources", "Third-party package sources"),
                            ("update_hooks", "APT hooks"),
                            ("invalidates_plans", "Earlier plans invalidated"),
                            ("no_rollback", "No rollback"),
                            ("clear_units", "Finished runs cleared"),
                            ("native_evidence", "Native evidence removed"),
                            ("kept_units", "Units left in place"),
                            ("site_account", "Site user and group"),
                            ("site_directories", "Site directories"),
                            ("site_files", "Configuration and content files"),
                            ("service_reload", "Service reloads"),
                            ("http_routing", "HTTP routing"),
                            ("acceptance_probe", "Temporary serving probe"),
                            ("isolation_limits", "Isolation limits"),
                            ("driver_modules", "PHP driver modules"),
                            ("database_principal", "Database principal"),
                            ("database_creation", "Database"),
                            ("database_privileges", "Database privileges"),
                            ("connection", "Connection instructions"),
                            ("catalog_inspection", "Read-only catalog inspection"),
                            ("challenge_route", "Challenge route"),
                            ("preimage_backup", "Recovery preimage"),
                            ("service_inhibition", "Service inhibition"),
                            ("renewal_integration", "Guarded renewal"),
                            ("compatible_clients", "Compatible controllers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PackageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "step",
                    models.CharField(
                        choices=[("install", "Install"), ("configure", "Configure")], max_length=10
                    ),
                ),
                ("package", models.CharField(max_length=100)),
                ("architecture", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=100)),
                ("origins", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="configurationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("admission_deadline_centiseconds", None),
                        ("uptime_centiseconds__isnull", True),
                    ),
                    (
                        "admission_deadline_centiseconds",
                        django.db.models.expressions.CombinedExpression(
                            models.F("uptime_centiseconds"), "+", models.Value(90000)
                        ),
                    ),
                    _connector="OR",
                ),
                name="plan_admission_deadline_fifteen_minutes",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible", False),
                    models.Q(
                        models.Q(("boot_id", ""), _negated=True),
                        ("uptime_centiseconds__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="eligible_plan_has_boot_and_deadline",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible", False),
                    models.Q(("privilege", "unavailable"), _negated=True),
                    _connector="OR",
                ),
                name="eligible_plan_has_privilege",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible", False), models.Q(("release", ""), _negated=True), _connector="OR"
                ),
                name="eligible_plan_has_release",
            ),
        ),
        migrations.AddField(
            model_name="applyrun",
            name="plan",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apply_run",
                to="bootstrap.configurationplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="planevidence",
            constraint=models.UniqueConstraint(
                fields=("plan", "kind"), name="unique_evidence_kind_per_plan"
            ),
        ),
        migrations.AddConstraint(
            model_name="packagetransition",
            constraint=models.UniqueConstraint(
                fields=("plan", "position"), name="unique_transition_position_per_plan"
            ),
        ),
    ]
