# Generated by Django 6.1.1 on 2026-09-28 13:14

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPreparation",
            fields=[
                (
                    "remoteoperation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="operations.remoteoperation",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx profile"),
                            ("php8.3", "PHP 8.3 profile (FPM and CLI)"),
                            ("metadata_refresh", "Package metadata refresh"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
            bases=("operations.remoteoperation",),
        ),
        migrations.CreateModel(
            name="ConfigurationPlan",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="plan",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx profile"),
                            ("php8.3", "PHP 8.3 profile (FPM and CLI)"),
                            ("metadata_refresh", "Package metadata refresh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("profile_revision", models.PositiveSmallIntegerField()),
                ("intent", models.CharField(max_length=200)),
                ("eligible", models.BooleanField()),
                ("no_changes", models.BooleanField(default=False)),
                ("ssh_alias", models.CharField(max_length=253, verbose_name="SSH alias")),
                ("host_key", models.CharField(max_length=200)),
                ("boot_id", models.CharField(blank=True, max_length=36)),
                ("uptime_centiseconds", models.BigIntegerField(null=True)),
                ("admission_deadline_centiseconds", models.BigIntegerField(null=True)),
                ("collected_at", models.DateTimeField()),
                ("admission_expires_at", models.DateTimeField()),
                ("os_name", models.CharField(blank=True, max_length=200)),
                ("architecture", models.CharField(blank=True, max_length=20)),
                ("apt_version", models.CharField(blank=True, max_length=100)),
                ("dpkg_version", models.CharField(blank=True, max_length=100)),
                ("systemd_version", models.CharField(blank=True, max_length=100)),
                (
                    "privilege",
                    models.CharField(
                        choices=[
                            ("root", "Root"),
                            ("sudo", "Noninteractive sudo"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("prepare_configurationplan", "Can prepare configuration plans"),
                    ("apply_configurationplan", "Can apply reviewed configuration plans"),
                    ("clear_native_results", "Can clear terminal native execution results"),
                ],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="PlanRootPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("installed", models.BooleanField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roots",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanRefusal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsupported_platform", "Unsupported platform"),
                            ("privilege", "Privilege unavailable"),
                            ("package_health", "Package database needs attention"),
                            ("held_package", "Held package"),
                            ("apt_hook", "Unknown APT hook"),
                            ("apt_configuration", "Unsupported APT configuration"),
                            ("package_source", "Unqualified package source"),
                            ("package_metadata", "Package indexes unavailable"),
                            ("installed_package_change", "Installed package would change"),
                            ("customized", "Customized configuration"),
                            ("leftover", "Leftover configuration"),
                            ("service_unit", "Service unit needs attention"),
                            ("listener", "Conflicting listener"),
                            ("simulation", "Package simulation refused"),
                            ("incomplete", "Incomplete evidence"),
                        ],
                        max_length=30,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refusals",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanPostcondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postconditions",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("platform", "Platform and boot"),
                            ("privilege", "Privilege"),
                            ("apt_configuration", "Effective APT configuration"),
                            ("apt_hooks", "APT hooks"),
                            ("apt_sources", "APT sources"),
                            ("apt_preferences", "APT preferences"),
                            ("package_indexes", "Package indexes"),
                            ("dpkg_status", "Relevant package states"),
                            ("package_holds", "Package holds"),
                            ("auto_marks", "Automatic installation marks"),
                            ("simulation", "APT simulation"),
                            ("web_configuration", "Web-stack configuration"),
                            ("service_units", "Service units"),
                            ("listeners", "Listeners"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("summary", models.CharField(max_length=300)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("no_changes", "No changes"),
                            ("packages", "Package installation"),
                            ("maintainer_start", "Package maintainer service start"),
                            ("http_listener", "Default HTTP listener"),
                            ("local_socket", "Local socket"),
                            ("service_enable", "Service enablement"),
                            ("service_start", "Service start"),
                            ("needrestart", "Native restart policy"),
                            ("index_update", "Package index update"),
                            ("update_hooks", "APT hooks"),
                            ("invalidates_plans", "Earlier plans invalidated"),
                            ("no_rollback", "No rollback"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PackageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "step",
                    models.CharField(
                        choices=[("install", "Install"), ("configure", "Configure")], max_length=10
                    ),
                ),
                ("package", models.CharField(max_length=100)),
                ("architecture", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=100)),
                ("origins", models.TextField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="configurationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("admission_deadline_centiseconds", None),
                        ("uptime_centiseconds__isnull", True),
                    ),
                    (
                        "admission_deadline_centiseconds",
                        django.db.models.expressions.CombinedExpression(
                            models.F("uptime_centiseconds"), "+", models.Value(90000)
                        ),
                    ),
                    _connector="OR",
                ),
                name="plan_admission_deadline_fifteen_minutes",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible", False),
                    models.Q(
                        models.Q(("boot_id", ""), _negated=True),
                        ("uptime_centiseconds__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="eligible_plan_has_boot_and_deadline",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible", False),
                    models.Q(("privilege", "unavailable"), _negated=True),
                    _connector="OR",
                ),
                name="eligible_plan_has_privilege",
            ),
        ),
        migrations.AddConstraint(
            model_name="planevidence",
            constraint=models.UniqueConstraint(
                fields=("plan", "kind"), name="unique_evidence_kind_per_plan"
            ),
        ),
        migrations.AddConstraint(
            model_name="packagetransition",
            constraint=models.UniqueConstraint(
                fields=("plan", "position"), name="unique_transition_position_per_plan"
            ),
        ),
    ]
