# Generated by Django 6.1.1 on 2026-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyrun",
            name="action",
            field=models.CharField(
                choices=[
                    ("nginx", "Nginx profile"),
                    ("php", "PHP profile (FPM and CLI)"),
                    ("php_source", "Approved PHP source setup"),
                    ("mariadb", "MariaDB profile"),
                    ("postgresql", "PostgreSQL profile"),
                    ("metadata_refresh", "Package metadata refresh"),
                    ("clear_results", "Clear finished bootstrap runs"),
                    ("site_http", "HTTP PHP site"),
                    ("php_mysql", "PHP MariaDB driver"),
                    ("php_pgsql", "PHP PostgreSQL driver"),
                    ("database_mariadb", "MariaDB site database"),
                    ("database_postgresql", "PostgreSQL site database"),
                    ("database_inspection", "Privileged database inspection"),
                    ("tls_challenge", "Site challenge route"),
                    ("certbot", "Certbot renewal setup"),
                    ("tls_readiness", "TLS readiness review"),
                    ("tls_staging", "Staging certificate order"),
                    ("tls_issuance", "Production certificate order"),
                    ("tls_activation", "HTTPS activation"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="configurationplan",
            name="action",
            field=models.CharField(
                choices=[
                    ("nginx", "Nginx profile"),
                    ("php", "PHP profile (FPM and CLI)"),
                    ("php_source", "Approved PHP source setup"),
                    ("mariadb", "MariaDB profile"),
                    ("postgresql", "PostgreSQL profile"),
                    ("metadata_refresh", "Package metadata refresh"),
                    ("clear_results", "Clear finished bootstrap runs"),
                    ("site_http", "HTTP PHP site"),
                    ("php_mysql", "PHP MariaDB driver"),
                    ("php_pgsql", "PHP PostgreSQL driver"),
                    ("database_mariadb", "MariaDB site database"),
                    ("database_postgresql", "PostgreSQL site database"),
                    ("database_inspection", "Privileged database inspection"),
                    ("tls_challenge", "Site challenge route"),
                    ("certbot", "Certbot renewal setup"),
                    ("tls_readiness", "TLS readiness review"),
                    ("tls_staging", "Staging certificate order"),
                    ("tls_issuance", "Production certificate order"),
                    ("tls_activation", "HTTPS activation"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planpreparation",
            name="action",
            field=models.CharField(
                choices=[
                    ("nginx", "Nginx profile"),
                    ("php", "PHP profile (FPM and CLI)"),
                    ("php_source", "Approved PHP source setup"),
                    ("mariadb", "MariaDB profile"),
                    ("postgresql", "PostgreSQL profile"),
                    ("metadata_refresh", "Package metadata refresh"),
                    ("clear_results", "Clear finished bootstrap runs"),
                    ("site_http", "HTTP PHP site"),
                    ("php_mysql", "PHP MariaDB driver"),
                    ("php_pgsql", "PHP PostgreSQL driver"),
                    ("database_mariadb", "MariaDB site database"),
                    ("database_postgresql", "PostgreSQL site database"),
                    ("database_inspection", "Privileged database inspection"),
                    ("tls_challenge", "Site challenge route"),
                    ("certbot", "Certbot renewal setup"),
                    ("tls_readiness", "TLS readiness review"),
                    ("tls_staging", "Staging certificate order"),
                    ("tls_issuance", "Production certificate order"),
                    ("tls_activation", "HTTPS activation"),
                ],
                max_length=20,
            ),
        ),
    ]
