# Generated by Django 6.1.1 on 2026-10-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0002_php_source_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyrun",
            name="php_supply",
            field=models.CharField(
                choices=[("ubuntu", "Ubuntu"), ("sury", "Unified PHP source")],
                default="ubuntu",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="applyrun",
            name="php_version",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="configurationplan",
            name="php_supply",
            field=models.CharField(
                choices=[("ubuntu", "Ubuntu"), ("sury", "Unified PHP source")],
                default="ubuntu",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="configurationplan",
            name="php_version",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="planpreparation",
            name="php_supply",
            field=models.CharField(
                choices=[("ubuntu", "Ubuntu"), ("sury", "Unified PHP source")],
                default="ubuntu",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="planpreparation",
            name="php_version",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
    ]
