# Generated by Django 6.1.1 on 2026-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0003_retain_php_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planevidence",
            name="kind",
            field=models.CharField(
                choices=[
                    ("php_source_recheck", "PHP source evidence rechecked before applying"),
                    ("platform", "Platform and boot"),
                    ("privilege", "Privilege"),
                    ("apt_configuration", "Effective APT configuration"),
                    ("apt_hooks", "APT hooks"),
                    ("apt_sources", "APT sources"),
                    ("apt_preferences", "APT preferences"),
                    ("package_indexes", "Package indexes"),
                    ("dpkg_status", "Relevant package states"),
                    ("package_holds", "Package holds"),
                    ("auto_marks", "Automatic installation marks"),
                    ("simulation", "APT simulation"),
                    ("web_configuration", "Web-stack configuration"),
                    ("service_units", "Service units"),
                    ("listeners", "Listeners"),
                    ("administration", "Administrative access"),
                    ("data_paths", "Data directories and option files"),
                    ("apt_revalidation", "APT evidence rechecked before applying"),
                    ("retained_units", "Retained bootstrap units"),
                    (
                        "package_revalidation",
                        "Package and service evidence rechecked before applying",
                    ),
                    ("site_revalidation", "Site evidence rechecked before applying"),
                    ("renewal_revalidation", "Renewal evidence rechecked before applying"),
                    ("external_reads", "Fresh DNS, addresses, clock and directory reads"),
                    ("lineage_revalidation", "Certificate lineage rechecked before applying"),
                    ("readiness_recheck", "Readiness reads rechecked before applying"),
                    ("nginx_closure", "Nginx configuration"),
                    ("fpm_closure", "PHP-FPM configuration"),
                    ("accounts", "Accounts and groups"),
                    ("allocation", "Account allocation policy"),
                    ("site_paths", "Site paths and ancestors"),
                    ("catalog", "Database catalog"),
                    (
                        "catalog_revalidation",
                        "Database catalog rechecked before and during applying",
                    ),
                    ("catalog_after", "Database catalog after applying"),
                    ("driver", "PHP driver rechecked before applying"),
                ],
                max_length=20,
            ),
        ),
    ]
