# Generated by Django 6.1.1 on 2026-10-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0011_wordpress_maintenance"),
        ("discovery", "0003_application_observations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyrun",
            name="action",
            field=models.CharField(
                choices=[
                    ("nginx", "Nginx profile"),
                    ("php", "PHP profile (FPM and CLI)"),
                    ("php_source", "Approved PHP source setup"),
                    ("php_default", "Server PHP default"),
                    ("site_php_switch", "Site PHP branch"),
                    ("node_runtime", "Node runtime"),
                    ("php_source_tools", "PHP source tools"),
                    ("mariadb", "MariaDB profile"),
                    ("postgresql", "PostgreSQL profile"),
                    ("metadata_refresh", "Package metadata refresh"),
                    ("clear_results", "Clear finished bootstrap runs"),
                    ("site_http", "HTTP PHP site"),
                    ("php_mysql", "PHP MariaDB driver"),
                    ("php_pgsql", "PHP PostgreSQL driver"),
                    ("database_mariadb", "MariaDB site database"),
                    ("database_postgresql", "PostgreSQL site database"),
                    ("database_inspection", "Privileged database inspection"),
                    ("tls_challenge", "Site challenge route"),
                    ("certbot", "Certbot renewal setup"),
                    ("tls_readiness", "TLS readiness review"),
                    ("tls_staging", "Staging certificate order"),
                    ("tls_issuance", "Production certificate order"),
                    ("tls_activation", "HTTPS activation"),
                    ("wpcli", "WP-CLI tool setup"),
                    ("php_wordpress", "WordPress PHP extensions"),
                    ("wordpress_install", "WordPress installation review"),
                    ("wordpress_finish", "WordPress installation Finish"),
                    ("wordpress_inspect", "WordPress inspection"),
                    ("wordpress_maintain", "WordPress maintenance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="configurationplan",
            name="action",
            field=models.CharField(
                choices=[
                    ("nginx", "Nginx profile"),
                    ("php", "PHP profile (FPM and CLI)"),
                    ("php_source", "Approved PHP source setup"),
                    ("php_default", "Server PHP default"),
                    ("site_php_switch", "Site PHP branch"),
                    ("node_runtime", "Node runtime"),
                    ("php_source_tools", "PHP source tools"),
                    ("mariadb", "MariaDB profile"),
                    ("postgresql", "PostgreSQL profile"),
                    ("metadata_refresh", "Package metadata refresh"),
                    ("clear_results", "Clear finished bootstrap runs"),
                    ("site_http", "HTTP PHP site"),
                    ("php_mysql", "PHP MariaDB driver"),
                    ("php_pgsql", "PHP PostgreSQL driver"),
                    ("database_mariadb", "MariaDB site database"),
                    ("database_postgresql", "PostgreSQL site database"),
                    ("database_inspection", "Privileged database inspection"),
                    ("tls_challenge", "Site challenge route"),
                    ("certbot", "Certbot renewal setup"),
                    ("tls_readiness", "TLS readiness review"),
                    ("tls_staging", "Staging certificate order"),
                    ("tls_issuance", "Production certificate order"),
                    ("tls_activation", "HTTPS activation"),
                    ("wpcli", "WP-CLI tool setup"),
                    ("php_wordpress", "WordPress PHP extensions"),
                    ("wordpress_install", "WordPress installation review"),
                    ("wordpress_finish", "WordPress installation Finish"),
                    ("wordpress_inspect", "WordPress inspection"),
                    ("wordpress_maintain", "WordPress maintenance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planpreparation",
            name="action",
            field=models.CharField(
                choices=[
                    ("nginx", "Nginx profile"),
                    ("php", "PHP profile (FPM and CLI)"),
                    ("php_source", "Approved PHP source setup"),
                    ("php_default", "Server PHP default"),
                    ("site_php_switch", "Site PHP branch"),
                    ("node_runtime", "Node runtime"),
                    ("php_source_tools", "PHP source tools"),
                    ("mariadb", "MariaDB profile"),
                    ("postgresql", "PostgreSQL profile"),
                    ("metadata_refresh", "Package metadata refresh"),
                    ("clear_results", "Clear finished bootstrap runs"),
                    ("site_http", "HTTP PHP site"),
                    ("php_mysql", "PHP MariaDB driver"),
                    ("php_pgsql", "PHP PostgreSQL driver"),
                    ("database_mariadb", "MariaDB site database"),
                    ("database_postgresql", "PostgreSQL site database"),
                    ("database_inspection", "Privileged database inspection"),
                    ("tls_challenge", "Site challenge route"),
                    ("certbot", "Certbot renewal setup"),
                    ("tls_readiness", "TLS readiness review"),
                    ("tls_staging", "Staging certificate order"),
                    ("tls_issuance", "Production certificate order"),
                    ("tls_activation", "HTTPS activation"),
                    ("wpcli", "WP-CLI tool setup"),
                    ("php_wordpress", "WordPress PHP extensions"),
                    ("wordpress_install", "WordPress installation review"),
                    ("wordpress_finish", "WordPress installation Finish"),
                    ("wordpress_inspect", "WordPress inspection"),
                    ("wordpress_maintain", "WordPress maintenance"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PhpRuntimeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("default_branch", models.CharField(blank=True, max_length=3)),
                ("default_path", models.CharField(blank=True, max_length=100)),
                ("default_mode", models.CharField(blank=True, max_length=6)),
                ("default_package", models.CharField(blank=True, max_length=30)),
                ("default_version", models.CharField(blank=True, max_length=100)),
                ("architecture", models.CharField(blank=True, max_length=6)),
                ("installed", models.CharField(blank=True, max_length=20)),
                ("supply", models.CharField(blank=True, max_length=6)),
                ("failure", models.TextField(blank=True)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                ("fresh", models.BooleanField(default=False)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SourceToolsSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("supply", models.CharField(max_length=6)),
                ("installed", models.BooleanField()),
                ("default_branch", models.CharField(blank=True, max_length=3)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_tools_selection",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
