# Generated by Django 6.1.1 on 2026-10-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0014_packagephpdefaultrequest"),
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtimechange",
            name="server",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="servers.server"
            ),
        ),
    ]
