# Generated by Django 6.1.1 on 2026-10-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap", "0015_runtime_server_removal"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimeplan",
            name="database_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="runtimeplan",
            name="database_engine",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="runtimerun",
            name="database_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="runtimerun",
            name="database_engine",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
