# Generated by Django 6.1.1 on 2026-09-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery"),
                            ("plan_preparation", "Plan preparation"),
                            ("apply", "Apply"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ssh_alias", models.CharField(max_length=253, verbose_name="SSH alias")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("reconciling", "Reconciling"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("failure", models.TextField(blank=True)),
                ("host_key", models.CharField(blank=True, max_length=200)),
                (
                    "server",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remote_operations",
                        to="servers.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at", "-pk"],
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "running", "reconciling"])),
                        fields=("server",),
                        name="one_active_remote_operation_per_server",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["discovery", "plan_preparation", "apply"])
                        ),
                        name="remote_operation_kind_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("server__isnull", False),
                            models.Q(("kind", "apply"), ("status__in", ["succeeded", "failed"])),
                            _connector="OR",
                        ),
                        name="only_finished_apply_runs_outlive_their_server",
                    ),
                ],
            },
        ),
    ]
