# Generated by Django 6.1.1 on 2026-09-29 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bootstrap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanAccountChange",
            fields=[
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="site_account",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("user", models.CharField(max_length=32)),
                ("group", models.CharField(max_length=32)),
                ("home", models.CharField(max_length=100)),
                ("login_shell", models.CharField(max_length=100)),
                ("command", models.TextField()),
                ("uid_min", models.PositiveIntegerField()),
                ("uid_max", models.PositiveIntegerField()),
                ("gid_min", models.PositiveIntegerField()),
                ("gid_max", models.PositiveIntegerField()),
                ("free_uids", models.PositiveIntegerField()),
                ("free_gids", models.PositiveIntegerField()),
                ("predicted_uid", models.PositiveIntegerField(null=True)),
                ("predicted_gid", models.PositiveIntegerField(null=True)),
                ("subordinate_ids", models.BooleanField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanSite",
            fields=[
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="site",
                        serialize=False,
                        to="bootstrap.configurationplan",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("php_version", models.CharField(max_length=10)),
                ("user", models.CharField(max_length=32)),
                ("document_root", models.CharField(max_length=100)),
                ("socket", models.CharField(max_length=100)),
                ("pool_name", models.CharField(max_length=24)),
                ("ipv6", models.BooleanField()),
                ("probe_token", models.CharField(max_length=32)),
                ("payload_bytes", models.PositiveIntegerField(null=True)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SiteRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="site_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("names", models.TextField()),
            ],
            options={
                "permissions": [
                    ("view_siteplan", "Can view site plans"),
                    ("prepare_siteplan", "Can prepare site plans"),
                    ("apply_siteplan", "Can apply site plans"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanDirectoryChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("path", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=32)),
                ("group", models.CharField(max_length=32)),
                ("mode", models.CharField(max_length=4)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_directories",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanFileChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("nginx_source", "Nginx site file"),
                            ("nginx_link", "Nginx enablement link"),
                            ("pool", "PHP-FPM pool"),
                            ("placeholder", "Placeholder page"),
                            ("probe", "Temporary serving probe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("file", "Regular file"), ("symlink", "Symbolic link")],
                        max_length=10,
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("group", models.CharField(max_length=32)),
                ("mode", models.CharField(blank=True, max_length=4)),
                ("link_target", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField(blank=True)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("preimage_absent", models.BooleanField(default=True)),
                ("temporary", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_files",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanSiteName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=253)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_names",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
    ]
