# Generated by Django 6.1.1 on 2026-10-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansite",
            name="convention_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="runsite",
            name="convention_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="siterequest",
            name="convention_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="siterequest",
            name="php_version",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
