# Generated by Django 6.1.1 on 2026-09-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("servers", "0003_unique_alias_field_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ssh_alias", models.CharField(max_length=253, verbose_name="SSH alias")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("failure", models.TextField(blank=True)),
                ("host_key", models.CharField(blank=True, max_length=200)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_attempts",
                        to="servers.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="DiscoverySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                (
                    "os_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("os_source", models.CharField(blank=True, max_length=100)),
                ("os_pretty_name", models.CharField(blank=True, max_length=200)),
                ("os_name", models.CharField(blank=True, max_length=200)),
                ("os_id", models.CharField(blank=True, max_length=100)),
                ("os_version_id", models.CharField(blank=True, max_length=100)),
                ("os_warning", models.TextField(blank=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="discovery.discoveryattempt",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="servers.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="discoveryattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("server",),
                name="discovery_one_active_attempt_per_server",
            ),
        ),
    ]
