# Generated by Django 6.1.1 on 2026-09-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryAttempt",
            fields=[
                (
                    "remoteoperation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="operations.remoteoperation",
                    ),
                ),
            ],
            bases=("operations.remoteoperation",),
        ),
        migrations.CreateModel(
            name="DiscoverySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                (
                    "os_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("os_source", models.CharField(blank=True, max_length=100)),
                ("os_pretty_name", models.CharField(blank=True, max_length=200)),
                ("os_name", models.CharField(blank=True, max_length=200)),
                ("os_id", models.CharField(blank=True, max_length=100)),
                ("os_version_id", models.CharField(blank=True, max_length=100)),
                ("os_warning", models.TextField(blank=True)),
                (
                    "arch_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("arch_value", models.CharField(blank=True, max_length=100)),
                ("arch_source", models.CharField(blank=True, max_length=100)),
                ("arch_warning", models.TextField(blank=True)),
                (
                    "cpu_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("cpu_count", models.PositiveIntegerField(blank=True, null=True)),
                ("cpu_source", models.CharField(blank=True, max_length=100)),
                ("cpu_warning", models.TextField(blank=True)),
                (
                    "memory_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("memory_bytes", models.BigIntegerField(blank=True, null=True)),
                ("memory_source", models.CharField(blank=True, max_length=100)),
                ("memory_warning", models.TextField(blank=True)),
                (
                    "filesystem_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("filesystem_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("filesystem_avail_bytes", models.BigIntegerField(blank=True, null=True)),
                ("filesystem_source", models.CharField(blank=True, max_length=100)),
                ("filesystem_warning", models.TextField(blank=True)),
                (
                    "nginx_site_files_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("nginx_site_files_source", models.TextField(blank=True)),
                ("nginx_site_files_warning", models.TextField(blank=True)),
                (
                    "php_fpm_pools_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("php_fpm_pools_source", models.TextField(blank=True)),
                ("php_fpm_pools_warning", models.TextField(blank=True)),
                (
                    "sites_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("sites_source", models.TextField(blank=True)),
                ("sites_warning", models.TextField(blank=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="discovery.discoveryattempt",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="servers.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ComponentObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx"),
                            ("php-fpm", "PHP-FPM"),
                            ("mariadb", "MariaDB"),
                            ("postgresql", "PostgreSQL"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "package_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("packages", models.TextField(blank=True)),
                ("package_source", models.CharField(blank=True, max_length=500)),
                ("package_warning", models.TextField(blank=True)),
                (
                    "service_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("service_source", models.TextField(blank=True)),
                ("service_warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="NginxSiteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("server_names", models.TextField(blank=True)),
                ("listens", models.TextField(blank=True)),
                ("source", models.CharField(max_length=500)),
                ("warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nginx_site_files",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="PhpFpmPoolObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("listen", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(max_length=500)),
                ("warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="php_fpm_pools",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ServiceUnitObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("load_state", models.CharField(max_length=20)),
                ("active_state", models.CharField(max_length=20)),
                ("sub_state", models.CharField(max_length=40)),
                ("unit_file_state", models.CharField(blank=True, max_length=20)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_units",
                        to="discovery.componentobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="SiteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("server_names", models.TextField(blank=True)),
                ("document_root", models.CharField(blank=True, max_length=200)),
                ("fastcgi_socket", models.CharField(blank=True, max_length=200)),
                ("php_version", models.CharField(max_length=20)),
                ("pool_user", models.CharField(blank=True, max_length=32)),
                ("pool_group", models.CharField(blank=True, max_length=32)),
                ("uid", models.PositiveIntegerField(blank=True, null=True)),
                ("gid", models.PositiveIntegerField(blank=True, null=True)),
                ("home", models.CharField(blank=True, max_length=200)),
                ("shell", models.CharField(blank=True, max_length=200)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="SiteResourceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("nginx_enabled", "Nginx enablement"),
                            ("nginx_source", "Nginx site file"),
                            ("fastcgi", "FastCGI parameters"),
                            ("ancestors", "Parent directories"),
                            ("boundary", "Site directory"),
                            ("document_root", "Document root"),
                            ("private", "Private directory"),
                            ("pool", "PHP-FPM pool"),
                            ("socket", "PHP-FPM socket"),
                            ("user", "Site user"),
                            ("password", "Locked password"),
                            ("exclusive", "Names, root and socket not shared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("conforms", models.BooleanField()),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("file", "Regular file"),
                            ("directory", "Directory"),
                            ("symlink", "Symbolic link"),
                            ("socket", "Socket"),
                            ("other", "Other file type"),
                        ],
                        max_length=10,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=32)),
                ("group", models.CharField(blank=True, max_length=32)),
                ("mode", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("link_target", models.CharField(blank=True, max_length=200)),
                ("source", models.TextField()),
                ("warning", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="discovery.siteobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="discoverysnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("os_status", "absent"), _negated=True),
                    models.Q(("arch_status", "absent"), _negated=True),
                    models.Q(("cpu_status", "absent"), _negated=True),
                    models.Q(("memory_status", "absent"), _negated=True),
                    models.Q(("filesystem_status", "absent"), _negated=True),
                ),
                name="snapshot_attributes_never_absent",
            ),
        ),
        migrations.AddConstraint(
            model_name="nginxsiteobservation",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "name"), name="unique_nginx_site_file_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="phpfpmpoolobservation",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "version", "name"), name="unique_php_fpm_pool_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceunitobservation",
            constraint=models.UniqueConstraint(
                fields=("component", "name"), name="unique_service_unit_per_component"
            ),
        ),
        migrations.AddConstraint(
            model_name="siteobservation",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "identifier"), name="unique_site_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="siteresourceobservation",
            constraint=models.UniqueConstraint(
                fields=("site", "resource"), name="unique_resource_per_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="siteresourceobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("conforms", False), ("status", "observed"), _connector="OR"),
                name="only_observed_resources_conform",
            ),
        ),
        migrations.CreateModel(
            name="SiteDatabaseObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        blank=True,
                        choices=[("mariadb", "MariaDB"), ("postgresql", "PostgreSQL")],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("conforms", models.BooleanField()),
                ("principal", models.CharField(blank=True, max_length=100)),
                ("database", models.CharField(blank=True, max_length=100)),
                ("authentication", models.CharField(blank=True, max_length=200)),
                ("privileges", models.TextField(blank=True)),
                ("character_set", models.CharField(blank=True, max_length=40)),
                ("collation", models.CharField(blank=True, max_length=100)),
                ("owner", models.CharField(blank=True, max_length=100)),
                ("source", models.TextField()),
                ("warning", models.TextField(blank=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database",
                        to="discovery.siteobservation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("conforms", False), ("status", "observed"), _connector="OR"
                        ),
                        name="only_observed_databases_conform",
                    )
                ],
            },
        ),
    ]
