# Generated by Django 6.1.1 on 2026-09-27 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ssh_alias", models.CharField(max_length=253, verbose_name="SSH alias")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("failure", models.TextField(blank=True)),
                ("host_key", models.CharField(blank=True, max_length=200)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_attempts",
                        to="servers.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="DiscoverySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                (
                    "os_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("os_source", models.CharField(blank=True, max_length=100)),
                ("os_pretty_name", models.CharField(blank=True, max_length=200)),
                ("os_name", models.CharField(blank=True, max_length=200)),
                ("os_id", models.CharField(blank=True, max_length=100)),
                ("os_version_id", models.CharField(blank=True, max_length=100)),
                ("os_warning", models.TextField(blank=True)),
                (
                    "arch_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("arch_value", models.CharField(blank=True, max_length=100)),
                ("arch_source", models.CharField(blank=True, max_length=100)),
                ("arch_warning", models.TextField(blank=True)),
                (
                    "cpu_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("cpu_count", models.PositiveIntegerField(blank=True, null=True)),
                ("cpu_source", models.CharField(blank=True, max_length=100)),
                ("cpu_warning", models.TextField(blank=True)),
                (
                    "memory_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("memory_bytes", models.BigIntegerField(blank=True, null=True)),
                ("memory_source", models.CharField(blank=True, max_length=100)),
                ("memory_warning", models.TextField(blank=True)),
                (
                    "filesystem_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("filesystem_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("filesystem_avail_bytes", models.BigIntegerField(blank=True, null=True)),
                ("filesystem_source", models.CharField(blank=True, max_length=100)),
                ("filesystem_warning", models.TextField(blank=True)),
                (
                    "nginx_site_files_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("nginx_site_files_source", models.CharField(blank=True, max_length=500)),
                ("nginx_site_files_warning", models.TextField(blank=True)),
                (
                    "php_fpm_pools_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("php_fpm_pools_source", models.CharField(blank=True, max_length=500)),
                ("php_fpm_pools_warning", models.TextField(blank=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="discovery.discoveryattempt",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="servers.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("os_status", "absent"), _negated=True),
                            models.Q(("arch_status", "absent"), _negated=True),
                            models.Q(("cpu_status", "absent"), _negated=True),
                            models.Q(("memory_status", "absent"), _negated=True),
                            models.Q(("filesystem_status", "absent"), _negated=True),
                        ),
                        name="snapshot_attributes_never_absent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponentObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx"),
                            ("php-fpm", "PHP-FPM"),
                            ("mariadb", "MariaDB"),
                            ("postgresql", "PostgreSQL"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "package_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("packages", models.TextField(blank=True)),
                ("package_source", models.CharField(blank=True, max_length=500)),
                ("package_warning", models.TextField(blank=True)),
                (
                    "service_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("units", models.TextField(blank=True)),
                ("service_source", models.TextField(blank=True)),
                ("service_warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="NginxSiteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("server_names", models.TextField(blank=True)),
                ("listens", models.TextField(blank=True)),
                ("source", models.CharField(max_length=500)),
                ("warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nginx_site_files",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="PhpFpmPoolObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("listen", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(max_length=500)),
                ("warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="php_fpm_pools",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="discoveryattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("server",),
                name="discovery_one_active_attempt_per_server",
            ),
        ),
        migrations.AddConstraint(
            model_name="nginxsiteobservation",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "name"), name="unique_nginx_site_file_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="phpfpmpoolobservation",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "version", "name"), name="unique_php_fpm_pool_per_snapshot"
            ),
        ),
    ]
