# Generated by Django 6.1.1 on 2026-10-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentobservation",
            name="deviations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="componentobservation",
            name="managed",
            field=models.BooleanField(default=True),
        ),
    ]
