# Generated by Django 6.1.1 on 2026-09-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoverysnapshot",
            name="sites_source",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="sites_status",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("inaccessible", "Inaccessible"),
                    ("absent", "Absent"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="sites_warning",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="SiteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=24)),
                ("server_names", models.TextField(blank=True)),
                ("document_root", models.CharField(blank=True, max_length=200)),
                ("fastcgi_socket", models.CharField(blank=True, max_length=200)),
                ("php_version", models.CharField(max_length=20)),
                ("pool_user", models.CharField(blank=True, max_length=32)),
                ("pool_group", models.CharField(blank=True, max_length=32)),
                ("uid", models.PositiveIntegerField(blank=True, null=True)),
                ("gid", models.PositiveIntegerField(blank=True, null=True)),
                ("home", models.CharField(blank=True, max_length=200)),
                ("shell", models.CharField(blank=True, max_length=200)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="SiteResourceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("nginx_enabled", "Nginx enablement"),
                            ("nginx_source", "Nginx site file"),
                            ("fastcgi", "FastCGI parameters"),
                            ("boundary", "Site directory"),
                            ("document_root", "Document root"),
                            ("private", "Private directory"),
                            ("pool", "PHP-FPM pool"),
                            ("socket", "PHP-FPM socket"),
                            ("user", "Site user"),
                            ("exclusive", "Names, root and socket not shared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("conforms", models.BooleanField()),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("file", "Regular file"),
                            ("directory", "Directory"),
                            ("symlink", "Symbolic link"),
                            ("socket", "Socket"),
                            ("other", "Other file type"),
                        ],
                        max_length=10,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=32)),
                ("group", models.CharField(blank=True, max_length=32)),
                ("mode", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("link_target", models.CharField(blank=True, max_length=200)),
                ("source", models.TextField()),
                ("warning", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="discovery.siteobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="siteobservation",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "identifier"), name="unique_site_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="siteresourceobservation",
            constraint=models.UniqueConstraint(
                fields=("site", "resource"), name="unique_resource_per_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="siteresourceobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("conforms", False), ("status", "observed"), _connector="OR"),
                name="only_observed_resources_conform",
            ),
        ),
    ]
