# Generated by Django 6.1.1 on 2026-10-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteobservation",
            name="convention_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
