# Generated by Django 6.1.1 on 2026-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoverysnapshot",
            name="arch_source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="arch_status",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("inaccessible", "Inaccessible"),
                    ("absent", "Absent"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="arch_value",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="arch_warning",
            field=models.TextField(
                blank=True, default="Architecture was not collected with this snapshot."
            ),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="cpu_count",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="cpu_source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="cpu_status",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("inaccessible", "Inaccessible"),
                    ("absent", "Absent"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="cpu_warning",
            field=models.TextField(
                blank=True, default="CPU count was not collected with this snapshot."
            ),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="filesystem_avail_bytes",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="filesystem_path",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="filesystem_size_bytes",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="filesystem_source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="filesystem_status",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("inaccessible", "Inaccessible"),
                    ("absent", "Absent"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="filesystem_warning",
            field=models.TextField(
                blank=True, default="Filesystem capacity was not collected with this snapshot."
            ),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="memory_bytes",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="memory_source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="memory_status",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("inaccessible", "Inaccessible"),
                    ("absent", "Absent"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="memory_warning",
            field=models.TextField(
                blank=True, default="Memory was not collected with this snapshot."
            ),
        ),
    ]
