# Generated by Django 6.1.1 on 2026-10-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0002_siteobservation_convention_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteobservation",
            name="canonical_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="siteobservation",
            name="routing",
            field=models.CharField(
                choices=[
                    ("unrecognized", "Not a convention form"),
                    ("php", "Generic PHP"),
                    ("wordpress_gate", "WordPress behind the provisioning gate"),
                    ("wordpress", "WordPress"),
                ],
                default="unrecognized",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SiteApplicationObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("absent", "Absent"),
                            ("candidate", "Candidate, unverified"),
                            ("partial", "Partial"),
                            ("installed", "Installed"),
                            ("blocked", "Blocked"),
                            ("unreadable", "Unreadable"),
                        ],
                        max_length=12,
                    ),
                ),
                ("core_version", models.CharField(blank=True, max_length=40)),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("not_observed", "Not observed"),
                            ("qualified", "Qualified"),
                            ("newer", "Newer than qualified"),
                            ("older", "Older than qualified"),
                            ("unrecognized", "Not a release version"),
                        ],
                        default="not_observed",
                        max_length=14,
                    ),
                ),
                (
                    "loader",
                    models.CharField(
                        choices=[
                            ("not_read", "Not read"),
                            ("absent", "Absent"),
                            ("exact", "The fixed loader"),
                            ("other", "Not the fixed loader"),
                        ],
                        default="not_read",
                        max_length=10,
                    ),
                ),
                (
                    "configuration",
                    models.CharField(
                        choices=[
                            ("not_read", "Not read"),
                            ("absent", "Absent"),
                            ("supported", "Supported grammar"),
                            ("unsupported", "Not the supported grammar"),
                        ],
                        default="not_read",
                        max_length=12,
                    ),
                ),
                ("configuration_digest", models.CharField(blank=True, max_length=64)),
                ("markers_present", models.PositiveSmallIntegerField(default=0)),
                ("markers_total", models.PositiveSmallIntegerField(default=0)),
                (
                    "schema",
                    models.CharField(
                        choices=[
                            ("not_read", "Not read"),
                            ("absent", "No core tables"),
                            ("partial", "Some core tables"),
                            ("complete", "Core tables and columns"),
                            ("altered", "Altered or ambiguous"),
                        ],
                        default="not_read",
                        max_length=10,
                    ),
                ),
                ("tables_present", models.PositiveSmallIntegerField(default=0)),
                ("site_url", models.CharField(blank=True, max_length=200)),
                ("home_url", models.CharField(blank=True, max_length=200)),
                ("blocked", models.TextField(blank=True)),
                ("limits", models.TextField(blank=True)),
                ("source", models.TextField(blank=True)),
                ("warning", models.TextField(blank=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="discovery.siteobservation",
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
            },
        ),
    ]
