# Generated by Django 6.1.1 on 2026-09-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0002_discoverysnapshot_arch_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx"),
                            ("php-fpm", "PHP-FPM"),
                            ("mariadb", "MariaDB"),
                            ("postgresql", "PostgreSQL"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "package_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("packages", models.TextField(blank=True)),
                ("package_source", models.CharField(blank=True, max_length=500)),
                ("package_warning", models.TextField(blank=True)),
                (
                    "service_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("units", models.TextField(blank=True)),
                ("service_source", models.CharField(blank=True, max_length=500)),
                ("service_warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
