# Generated by Django 6.1.1 on 2026-10-06 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0002_componentobservation_deviations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitedatabaseobservation",
            name="authentication_line",
        ),
    ]
