# Generated by Django 6.1.1 on 2026-10-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0003_remove_sitedatabaseobservation_authentication_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedatabaseobservation",
            name="partial",
            field=models.BooleanField(default=False),
        ),
    ]
