# Generated by Django 6.1.1 on 2026-09-27 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0003_serviceobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoverysnapshot",
            name="pools_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="pools_status",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("inaccessible", "Inaccessible"),
                    ("absent", "Absent"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="pools_warning",
            field=models.TextField(
                blank=True, default="Pool observations were not collected with this snapshot."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="sites_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="sites_status",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("inaccessible", "Inaccessible"),
                    ("absent", "Absent"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverysnapshot",
            name="sites_warning",
            field=models.TextField(
                blank=True, default="Site observations were not collected with this snapshot."
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PoolObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("listen", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(max_length=500)),
                ("warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "version", "name"), name="unique_pool_per_snapshot"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("inaccessible", "Inaccessible"),
                            ("absent", "Absent"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("server_names", models.TextField(blank=True)),
                ("listens", models.TextField(blank=True)),
                ("source", models.CharField(max_length=500)),
                ("warning", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="discovery.discoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "name"), name="unique_site_per_snapshot"
                    )
                ],
            },
        ),
    ]
