# Generated by Django 6.1.1 on 2026-09-30 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bootstrap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseRequest",
            fields=[
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="database_request",
                        serialize=False,
                        to="bootstrap.planpreparation",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_databaseplan", "Can view database plans"),
                    ("prepare_databaseplan", "Can prepare database plans"),
                    ("apply_databaseplan", "Can apply database plans"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlanDriverPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=24)),
                ("user", models.CharField(max_length=32)),
                ("socket", models.CharField(max_length=100)),
                ("default", models.BooleanField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_pools",
                        to="bootstrap.configurationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "default_permissions": (),
            },
        ),
    ]
