# Generated by Django 6.1.1 on 2026-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("databases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plandatabasebinding",
            name="php_supply",
            field=models.CharField(default="ubuntu", max_length=10),
        ),
        migrations.AddField(
            model_name="plandatabasebinding",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="rundatabasebinding",
            name="php_supply",
            field=models.CharField(default="ubuntu", max_length=10),
        ),
        migrations.AddField(
            model_name="rundatabasebinding",
            name="site_revision",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
