# Generated by Django 6.1.1 on 2026-10-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("databases", "0002_plandatabasebinding_php_supply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaserequest",
            name="php_supply",
            field=models.CharField(default="ubuntu", max_length=10),
        ),
        migrations.AddField(
            model_name="databaserequest",
            name="php_version",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
